### ISSUE TITLE
no current support for On Button Click trigger on items with no buttons

### ISSUE THREAD

**Issue by etiquettestartshere** [FurtherV/scriptable-items#3]
Currently throws this error:
![image](https://github.com/FurtherV/scriptable-items/assets/148253744/58840a64-9852-40e8-98d8-51fa0fa0f2c7)

An alternative to 
```js
const buttonContainer = el.querySelector(".card-buttons");
/*...*/
buttonContainer.append(newButton);
```
could be employed in cases where `buttonContainer` is not found to allow scripts to be added to items that do not already have buttons such as damage or attack roll buttons. The most common use case I can think of would be things like trinkets and spells, where you want the 'workflow' of printing the item in chat, but it has no attack/damage/AE, and instead has a script to be run.

**Comment by FurtherV** [comment]
I guess an easy fix for this would be just adding a button container to the chat card if none is found.
