### ISSUE TITLE
add a setting to hide 'Execute' from button labels

### ISSUE THREAD

**Issue by etiquettestartshere** [FurtherV/scriptable-items#4]
While it is explicit that a macro is being executed by the `Execute <script name>` syntax of button creation, the word is long and technical, and some users may prefer if the only text label on the button is the name of the script itself.

![image](https://github.com/FurtherV/scriptable-items/assets/148253744/369552f4-54e6-49d3-be7f-369ea1a55986)
![image](https://github.com/FurtherV/scriptable-items/assets/148253744/cf17c340-e3ff-4b14-ace4-346ae824c6f4)

**Comment by FurtherV** [comment]
Sounds good, would making both the label prefix (can be empty) and the icon visibility / type a world setting be a good idea?

**Comment by etiquettestartshere** [comment]
I like the icon you chose, it illustrates the function of the button and looks right alongside the system's icons, but more options is always better imo (at least if you dont plan to add tons and tons of settings for other things in the future).

The label being a prefix that can be empty sounds good if im understanding it right

**Comment by FurtherV** [comment]
Yeah so in d9abe7e46449b571b8333564e75adb6debfc9a66 the requested changes are implemented. You can take a look if you want. Basically, if the prefix field in the module's settings is empty, neither the prefix nor its following whitespace are added to the HTML.
- `Execute` => `ICON Execute SCRIPT_NAME`
- `` => `ICON SCRIPT_NAME`

It does not affect already created chat messages, just new ones though.
